/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpacesSpaceIdRouteRouteImport } from './routes/spaces/$spaceId/route'
import { Route as SpacesSpaceIdIndexRouteImport } from './routes/spaces/$spaceId/index'
import { Route as SpacesSpaceIdBoardsBoardIdRouteImport } from './routes/spaces/$spaceId/boards/$boardId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSpaceIdRouteRoute = SpacesSpaceIdRouteRouteImport.update({
  id: '/spaces/$spaceId',
  path: '/spaces/$spaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSpaceIdIndexRoute = SpacesSpaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpacesSpaceIdRouteRoute,
} as any)
const SpacesSpaceIdBoardsBoardIdRoute =
  SpacesSpaceIdBoardsBoardIdRouteImport.update({
    id: '/boards/$boardId',
    path: '/boards/$boardId',
    getParentRoute: () => SpacesSpaceIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/spaces/$spaceId': typeof SpacesSpaceIdRouteRouteWithChildren
  '/spaces/$spaceId/': typeof SpacesSpaceIdIndexRoute
  '/spaces/$spaceId/boards/$boardId': typeof SpacesSpaceIdBoardsBoardIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/spaces/$spaceId': typeof SpacesSpaceIdIndexRoute
  '/spaces/$spaceId/boards/$boardId': typeof SpacesSpaceIdBoardsBoardIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/spaces/$spaceId': typeof SpacesSpaceIdRouteRouteWithChildren
  '/spaces/$spaceId/': typeof SpacesSpaceIdIndexRoute
  '/spaces/$spaceId/boards/$boardId': typeof SpacesSpaceIdBoardsBoardIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/spaces/$spaceId'
    | '/spaces/$spaceId/'
    | '/spaces/$spaceId/boards/$boardId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/spaces/$spaceId'
    | '/spaces/$spaceId/boards/$boardId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/spaces/$spaceId'
    | '/spaces/$spaceId/'
    | '/spaces/$spaceId/boards/$boardId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SpacesSpaceIdRouteRoute: typeof SpacesSpaceIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$spaceId': {
      id: '/spaces/$spaceId'
      path: '/spaces/$spaceId'
      fullPath: '/spaces/$spaceId'
      preLoaderRoute: typeof SpacesSpaceIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$spaceId/': {
      id: '/spaces/$spaceId/'
      path: '/'
      fullPath: '/spaces/$spaceId/'
      preLoaderRoute: typeof SpacesSpaceIdIndexRouteImport
      parentRoute: typeof SpacesSpaceIdRouteRoute
    }
    '/spaces/$spaceId/boards/$boardId': {
      id: '/spaces/$spaceId/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/spaces/$spaceId/boards/$boardId'
      preLoaderRoute: typeof SpacesSpaceIdBoardsBoardIdRouteImport
      parentRoute: typeof SpacesSpaceIdRouteRoute
    }
  }
}

interface SpacesSpaceIdRouteRouteChildren {
  SpacesSpaceIdIndexRoute: typeof SpacesSpaceIdIndexRoute
  SpacesSpaceIdBoardsBoardIdRoute: typeof SpacesSpaceIdBoardsBoardIdRoute
}

const SpacesSpaceIdRouteRouteChildren: SpacesSpaceIdRouteRouteChildren = {
  SpacesSpaceIdIndexRoute: SpacesSpaceIdIndexRoute,
  SpacesSpaceIdBoardsBoardIdRoute: SpacesSpaceIdBoardsBoardIdRoute,
}

const SpacesSpaceIdRouteRouteWithChildren =
  SpacesSpaceIdRouteRoute._addFileChildren(SpacesSpaceIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SpacesSpaceIdRouteRoute: SpacesSpaceIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
